[package]
name = "todoclist"
version = "0.1.0"
authors = ["rodeldev <rodelbusiness@hotmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"